apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: aareg-teknisk-historikk
  namespace: arbeidsforhold
  labels:
    team: arbeidsforhold
spec:
  image: {{image}}

  port: 8080

  ingresses:
    - https://aareg-teknisk-historikk.nav.no

  env:
    - name: APP_NAME
      value: aareg-teknisk-historikk

    - name: APP_URL_AAREG_SERVICES
      value: https://aareg-services.prod-fss-pub.nais.io
    - name: APP_TEXAS_TARGET_AAREG_SERVICES
      value: api://prod-fss.arbeidsforhold.aareg-services-nais/.default

    - name: APP_URL_AAREG_TILGANGSKONTROLL
      value: https://aareg-tilgangskontroll.intern.nav.no
    - name: APP_TEXAS_TARGET_AAREG_TILGANGSKONTROLL
      value: api://prod-gcp.arbeidsforhold.aareg-tilgangskontroll/.default

    - name: APP_SECURITY_OIDC_IDP_MASKINPORTEN_ISSUERURL
      value: https://maskinporten.no/
    - name: APP_SECURITY_OIDC_IDP_MASKINPORTEN_JWKSETURI
      value: https://maskinporten.no/jwks

  replicas:
    min: 2
    max: 2
    cpuThresholdPercentage: 50

  liveness:
    path: /actuator/health/liveness
    initialDelay: 60
    periodSeconds: 2
    timeout: 2
    failureThreshold: 30

  readiness:
    path: /actuator/health/readiness
    initialDelay: 60
    periodSeconds: 2
    timeout: 2
    failureThreshold: 30

  resources:
    requests:
      cpu: 100m
      memory: 512mi
    limits:
      memory: 4Gi

  prometheus:
    enabled: true
    path: actuator/prometheus

  azure:
    application:
      enabled: true

  maskinporten:
    enabled: true
    scopes:
      exposes:
        - name: v1/arbeidsforhold/tekniskhistorikk
          enabled: true
          product: aareg
          atMaxAge: 180
          delegationSource: altinn
          separator: "/"
          consumers:
            - name: Fellesordningen for AFP
              orgno: "987414502"

  accessPolicy:
    outbound:
      rules:
        - application: aareg-tilgangskontroll
          namespace: arbeidsforhold
          cluster: prod-gcp
        - application: logging
          namespace: nais-system
      external:
        - host: aareg-services.prod-fss-pub.nais.io
