springdoc:
  swagger-ui:
    url: /openapi-spec.yaml
  api-docs:
    path: /api-docs
management:
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
  endpoints:
    web:
      exposure:
        include: health,prometheus
  endpoint:
    health:
      probes:
        enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  prometheus:
    metrics:
      export:
        enabled: true
spring:
  main:
    banner-mode: off
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${MASKINPORTEN_ISSUER}
          jwk-set-uri: ${MASKINPORTEN_JWKS_URI}