management:
  otlp:
    metrics:
      export:
        url: http://opentelemetry-collector.nais-system:4318/v1/metrics
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
  endpoints:
    web:
      exposure:
        include: health,prometheus
  endpoint:
    health:
      probes:
        enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  prometheus:
    metrics:
      export:
        enabled: true
spring:
  main:
    banner-mode: off